language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
before_script:
- npm install -g yarn
install:
- yarn
script:
- yarn build
- yarn lint
- yarn test
<<<<<<< HEAD
before_install:
- openssl aes-256-cbc -K $encrypted_98eb5aa6bfa6_key -iv $encrypted_98eb5aa6bfa6_iv
  -in .env.enc -out .env -d
=======
>>>>>>> upstream/develop
