name: CD
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.4.1
        with:
            ssh-private-key: ${{ secrets.CI_SSH }}
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7 #install the python needed
      - name: Checkout configs repo
        uses: actions/checkout@v2
        with:
          repository: forensic-architecture/configs
          ref: devops/ci-workflow
          token: ${{ secrets.CD_Workflow_PAT }} # `GitHub_PAT` is a secret that contains your PAT
          path: configs
      - name: Generate vault file
        run: python3 configs/generate_timemap_vault.py -f "configs/timemap" -p $PORT -SA "$SERVICE_ACCOUNT_EMAIL" -SPK "$SERVICE_ACCOUNT_PRIVATE_KEY"
        env:
          PORT: 4444
          SERVICE_ACCOUNT_EMAIL: ${{ secrets.SERVICE_ACCOUNT_EMAIL }} 
          SERVICE_ACCOUNT_PRIVATE_KEY: ${{ secrets.SERVICE_ACCOUNT_PRIVATE_KEY }}
      - name: Checkout devops repo
        uses: actions/checkout@v2
        with:
          repository: forensic-architecture/devops
          path: devops
      - name: Copy new config file
        run: cp vault.yml devops/deploy_timemap/vars/vault.yml
      - name: Install ansible
        run: sudo apt update &&
             sudo apt install software-properties-common &&
             sudo apt-add-repository --yes --update ppa:ansible/ansible &&
             sudo apt install ansible
      - name: Install devops dependencies
        run: python3 -m pip install jmespath && 
             ansible-galaxy install angstwad.docker_ubuntu &&
             sudo apt install gawk
      - name: Create hosts file
        run: cd devops/deploy_timemap && mkdir inventories && cd inventories &&
             echo -e "[$HOST]\n
             $IP_ADDRESS" > hosts
        env:
          HOST: fa_internal
          IP_ADDRESS: ${{secrets.INTERNAL_IP_ADDRESS}}
      - name: Read hosts file
        run: cat devops/deploy_timemap/inventories/hosts
      - name: Write key to file
        run: cd $HOME/.ssh && echo "$FADEV_SSH_PRIVATE_KEY" > fadev
        env:
          FADEV_SSH_PRIVATE_KEY: ${{ secrets.FADEV_SSH_PRIVATE_KEY }}  
      - name: Export env vars
        run: export ANSIBLE_HOST_GROUP="$HOST" &&
             export ANSIBLE_CONFIG=$HOME/work/datasheet-server/datasheet-server/devops/deploy_timemap/ansible.cfg &&
             export ANSIBLE_SSH_KEY_PATH=$HOME/.ssh/fadev &&
             export ANSIBLE_REMOTE_USER='fadev' &&
             export ANSIBLE_BECOME='yes'
        env:
          HOST: fa_internal
      - name: Check templates from vault file
        run: ansible-playbook -K devops/deploy_timemap/playbooks/check_templates.yml
      - name: Run ansible deploy
        run: ansible-playbook devops/deploy_timemap/playbooks/deploy_timemap.yml -v --extra-vars "ansible_become_pass=$FADEV_PWORD"
        env:
          FADEV_PWORD: ${{ secrets.FADEV_PWORD }}
            
