name: CD
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.4.1
        with:
            ssh-private-key: ${{ secrets.CI_SSH }}
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7 #install the python needed
      - name: Checkout configs repo
        uses: actions/checkout@v2
        with:
          repository: forensic-architecture/configs
          ref: devops/ci-workflow
          token: ${{ secrets.CD_Workflow_PAT }} # `GitHub_PAT` is a secret that contains your PAT
          path: configs
      - name: Generate vault file
        run: python3 configs/generate_timemap_vault.py -p $PORT -SA "$SERVICE_ACCOUNT_EMAIL" -SPK "$SERVICE_ACCOUNT_PRIVATE_KEY"
        env:
          PORT: 4444
          SERVICE_ACCOUNT_EMAIL: ${{secrets.SERVICE_ACCOUNT_EMAIL}} 
          SERVICE_ACCOUNT_PRIVATE_KEY: ${{secrets.SERVICE_ACCOUNT_PRIVATE_KEY}}
      - name: Checkout devops repo
        uses: actions/checkout@v2
        with:
          repository: forensic-architecture/devops
          path: devops
      - name: Copy new config file
        run: cp vault.yml devops/deploy_timemap/vars/vault.yml
      - name: Install ansible
        run: sudo apt update &&
             sudo apt install software-properties-common &&
             sudo apt-add-repository --yes --update ppa:ansible/ansible &&
             sudo apt install ansible
      - name: Install devops dependencies
        run: python3 -m pip install jmespath && 
             ansible-galaxy install angstwad.docker_ubuntu &&
             sudo apt install gawk
      - name: debugging
        run: cat vault.yml &&
             cd /.ssh && ls -a
